image: golang:1.15-alpine

variables:
  APP_NAME: go-simple-user-api
  APP_TEAM: games
  APP_REPO_PATH: git.garena.com/constantino.lana/go-simple-user-api

test:
  stage: test
  tags:
    - tutorial-ci
  script:
    - CGO_ENABLED=0 go test ./... -coverprofile=coverage.report.out
    - go tool cover -html=coverage-report.out -o coverage-report.html
    - go tool cover -func=coverage-report.out
  artifacts:
    paths:
      - coverage-report.html
      - expire-in:1 days
  coverage: "/\\(statements\\)\\s+\\d+.?\\d+%/"